### app render
http://localhost:3000/



### api main
http://localhost:3000/api/



### post new task
POST http://localhost:3000/api/task
content-type: application/json

{
    "description": "Lorem ipsum dolor set amet5",
    "complete": false
}



### get tasks
http://localhost:3000/api/tasks



### get task by id
http://localhost:3000/api/task/0



### patch task by id
PATCH http://localhost:3000/api/task/60
content-type: application/json

{
    "complete": true
}



### delete task by id
DELETE http://localhost:3000/api/task/3