### app render
http://localhost:3000/



### api main
http://localhost:3000/api/



### post new list
POST http://localhost:3000/api/list
content-type: application/json

{
    "name": "List"
}



### get lists
http://localhost:3000/api/lists



### get tasks of list
http://localhost:3000/api/tasks/clursn4i20001jp3jmckwu2a8



### post new task
POST http://localhost:3000/api/task
content-type: application/json

{
    "description": "Lorem ipsum dolor set amet5",
    "complete": false,
    "listId": "clursn4i20001jp3jmckwu2a8"
}



### get tasks
###http://localhost:3000/api/tasks



### get task by id
http://localhost:3000/api/task/0



### patch task by id
PATCH http://localhost:3000/api/task/60
content-type: application/json

{
    "complete": true
}



### delete task by id
DELETE http://localhost:3000/api/task/3